### ISSUE TITLE
Notes for 1.0

### ISSUE THREAD

**Issue by vbawol** [EpochModTeam/Epoch#583]
**Vehicles**
- [ ] Virtual Keys Tracking #766 #756 
- [x] Use A3 Dynamic Simulation? #727 

**Interaction**
- [ ] Add short delay and visible timer when interacting with Safes and Vehicles (lock/unlock). (rate limit PVC/REC calls) https://github.com/EpochModTeam/Epoch/issues/472
- [x] Add quick inventory hotbar to dynamic HUD. #234 

**Looting**
- [x] Add Sticks and Rocks to trash loot as this will make it possible to make a fireplace without needing a tool. #611 
- [x] loot positions on Altis have changed altitude. #588 
- [ ] A3 Buildings missing from EPOCH loot spawn tables #528 

**Base Building**
- [x] Snap angle can be off when snapping to object at an angle. #702 
- [x] base building improvments. #466 #199 #499 #181 #702 
- [ ] Add more maintenance options and configurable base maintenance costs.  (E + M) #226 

**Antagonists**
- [ ] Sharks could use a boost in speed and turning ability, use setVelocityTransformation. #178 

**NPC Traders**
- [ ] Add special trader categories (i.e. "blackmarket") items at higher prices #610 
- [x] Trader menu improvments:  Alphabetical / Numerical Trader Lists. https://github.com/EpochModTeam/Epoch/issues/120 Trader categories. https://github.com/EpochModTeam/Epoch/issues/414 https://github.com/EpochModTeam/Epoch/issues/283

**ADMIN PANEL / ANTI CHEAT**
- [ ] rework Anti teleport as it does not allow for normal usage of parachute, and causes issues with new APEX helicopter "blackfish". #338 
- [x] Frequency jammer, option in admin tools to see all jammers https://github.com/EpochModTeam/Epoch/issues/495

**Characters / Models**
- [x] Add additonal femal skins https://github.com/EpochModTeam/EpochCore/commit/635d238d5628cf8db9a08304fb9696b73b2f841e
- [x] One step is higher on stairs, can't run up while crouched #447 

**Magazine**
- [x] Performance Enhancing Drugs  #612
- [x] Smelting Toolkit #611 
- [x] Toxic Smoke grenade. #608
- [x] Anti Toxin. "Autoinjector 2mg Atropine or better 2mg Atropine+220mg Obidoxime(reduce toxity)" #608

**Crafting/Cooking**
- [x] Metal smelting recipes that require new smelting tools.
- [x] Crafting suggestions: barrel bomb #659
- [ ] Craft a harvested plant item into seeds, these seeds are placed into the cargo space of the garden.

**Misc**
- [x] Farming System: https://github.com/EpochModTeam/Epoch/issues/609

**Radiation**
- [x] radiation system #796

**Comment by raymix** [comment]
Found the cause for Crafting error. Caused purely because of lack of documentation on my part.

General rule of thumb is - When adding crafting items with new parts - make sure you also define recipe parts as actual existing parts.
In this case "ItemBriefcaseGold100oz" requires 1x "ItemBriefcaseE", but such part doesn't exist.
Solution: define - class ItemBriefcaseE: Part {...}

Will be fixed (together with 3D previews) in next push

**Comment by Vampurica** [comment]
Would using setAnimSpeedCoef on the sharks to speed up their animations be enough? It should make them faster.

setVelocityTransformation is pretty complex and seems like it would have to fire onEachFrame for each shark.

**Comment by ravmustang** [comment]
Barrel Bomb Upright and Horizontal added to core and crafting recipe added
https://github.com/EpochModTeam/EpochCore/pull/27
https://github.com/EpochModTeam/Epoch/pull/784
