### ISSUE TITLE
Final TODO for 1.0

### ISSUE THREAD

**Issue by vbawol** [EpochModTeam/Epoch#918]
***Models***
- [x] Half Wood floor seem to be missing geo lod, maybe needs mass or find components. (can walk though the sides of them)
- [x] Minor shadow glitch on Half wood floor. See Pic ![20171017054508_1](https://user-images.githubusercontent.com/3138624/31662310-72c12110-b303-11e7-9cda-ad157de5a5e2.jpg)

***Base Building***
- [x] Snapping issues are still seen while at an angle with half and quarter floors. The two half floors above snapped/saved this way ^
- [ ] Snapping issues between full floors

***Crafting***
- [x] Allow crafting all harvested plants into seeds.
- [x] smelting tools requirement not working and causing an error. @vbawol (and the crafting menu shows the inventory instead of the smelting tool.)

***Looting***
- [x] Malden and some A3 Buildings missing from EPOCH loot spawn tables #528
