### ISSUE TITLE
TODO part 2

### ISSUE THREAD

**Issue by vbawol** [EpochModTeam/Epoch#933]
***Code***
- [x] Radiation mask should reduce exposure to radiation and toxicity from the environment.
- [x] Satellite should be lootable. (Use sledge hammer to harvest)

***Configs***
- [x] Older female outfits lost their proper names display names.
- [x] New Female outfits have the same display name.

***Models***
- [x] cinder floor shadow seems to be smaller, showing light though when used as a ceiling.
- [x] The bunker "sewer" walls and other in-room props are still too bright compared to the bunker walls.

***Known Issues***
- [x] Snapping issues between quarter half and full floors.

**Comment by vbawol** [comment]
@Helion4 when you get time could you please look at the sewer, supply boxes, and generator bunkers? The sewer walls and other props are still too bright compared to the bunker walls.

**Comment by ravmustang** [comment]
The new female outfits were modified to correct displayName issue or lack thereof.
Older female uniforms were OK during my tests in inventory and admin panel.

https://github.com/EpochModTeam/EpochCore/commit/d8338913c64e2361ce565556f450aba86795f445

**Comment by vbawol** [comment]
Sweet, now just down to testing 🔢
